In [1]:
import numpy as np

In [2]:
# asXX
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
a = a.astype(np.float32,copy=False) #copy=False ?
print(a)

a = [1,2,3]
b = np.asarray(a) #asarray 和 array有什么区别？
print(b)
c = np.array(a)
print(c)

(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]
[1 2 3]
[1 2 3]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.fliplr(a) #左右对称置换
print(a.shape,b.shape)
print(a)
print(b)

(2, 3) (2, 3)
[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]


In [4]:
# Xstack
a0 = np.array([1,2,3])
a1 = np.array([4,5,6])
print("a0:",a0)
print("a1:",a1)

c = np.dstack((a0,a1)) #
print("dstack:",c)

c1 = np.hstack((a0,a1)) #Horizontal,水平
print("hstack:",c1)

c2 = np.vstack((a0,a1)) #Vertical，垂直
print("vstack:",c2)

c3 = np.concatenate((a0,a1), axis=0) #等价于hstack？
print("concatenate-0:",c3)

# c4 = np.concatenate((a0,a1), axis=1) #等价于vstack？
# print("concatenate-1:",c4) # AxisError: axis 1 is out of bounds for array of dimension 1

a0: [1 2 3]
a1: [4 5 6]
dstack: [[[1 4]
  [2 5]
  [3 6]]]
hstack: [1 2 3 4 5 6]
vstack: [[1 2 3]
 [4 5 6]]
concatenate-0: [1 2 3 4 5 6]


In [5]:
# image = image.transpose((2, 0, 1))
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c0 = a.transpose((1,0))
print('c0:',c0)

c0: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [6]:
a0 = np.array([1,0,0,1,1,1])
a1 = np.array([1.0,0,0,0,1,0])
acc = np.mean( (a0 == a1).astype(int) )
print(acc)

c = np.dot(a0, a1) / (np.linalg.norm(a0) * np.linalg.norm(a1))  #cosin距离
print(c)
d = np.dot(a0, a1)
e = np.linalg.norm(a0)
f = np.linalg.norm(a1)
print('d:',d)
print('e:',e)
print('f:',f)

0.6666666666666666
0.7071067811865475
d: 2.0
e: 2.0
f: 1.4142135623730951
