In [1]:
import numpy as np

In [15]:
#1.类型转换 asXX
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
a = a.astype(np.float32,copy=False) #copy=False ?
print("a:", a)

# asarray 和 array的主要区别？都是将数组转化为ndarray对象，
# 当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会，而是与参数共享同一个内存。
# https://stackoverflow.com/questions/14415741/numpy-array-vs-asarray
# a = [1,2,3]
b = np.asarray(a) 
print("b:",b)
c = np.array(a)
print("c:",c)

(2, 3)
a: [[1. 2. 3.]
 [4. 5. 6.]]
b: [1 2 3]
c: [1 2 3]


In [37]:
#2.各种数据合并: Xstack，concatenate
# https://drivingc.com/numpy/5af65a5c2392ec691e7279fb
# hstack()、vstack（）、stack（）、dstack（）、vsplit（）、concatenate（）
a0 = np.array([[1,2,3]])
a1 = np.array([[4,5,6]])
print("a0:",a0)
print("a1:",a1)

v = a0.reshape(-1,1)
print("v:", v.shape,v)

c = np.dstack((a0,a1)) # 等价于 np.concatenate(tup,axis=2)
print("dstack:",c.shape,c)

c1 = np.hstack((a0,a1)) #Horizontal,水平 等价于np.concatenate（tup,axis=1）
print("hstack:",c1.shape,c1)

c2 = np.vstack((a0,a1)) #Vertical，垂直 等价于np.concatenate(tup,axis=0) 
print("vstack:",c2.shape,c2)

c3 = np.concatenate((a0,a1), axis=0) #等价于hstack？
print("concatenate-0:",c3.shape,c3)

a0 = np.array([[1,2,3]])
a1 = np.array([[4,5,6]])
c4 = np.concatenate((a0,a1), axis=0) 
print("concatenate-0:",c4) # AxisError: axis 1 is out of bounds for array of dimension 1
c5 = np.concatenate((a0,a1), axis=1) 
print("concatenate-1:",c5) # AxisError: axis 1 is out of bounds for array of dimension 1

a0: [[1 2 3]]
a1: [[4 5 6]]
v: (3, 1) [[1]
 [2]
 [3]]
dstack: (1, 3, 2) [[[1 4]
  [2 5]
  [3 6]]]
hstack: (1, 6) [[1 2 3 4 5 6]]
vstack: (2, 3) [[1 2 3]
 [4 5 6]]
concatenate-0: (2, 3) [[1 2 3]
 [4 5 6]]
concatenate-0: [[1 2 3]
 [4 5 6]]
concatenate-1: [[1 2 3 4 5 6]]


In [25]:
#3.各种转置变换
a = np.array([[1,2,3],[4,5,6]])
b = np.fliplr(a) #左右对称置换
print(a.shape,b.shape)
print('a:', a)
print('b:', b)

# image = image.transpose((2, 0, 1))
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c0 = a.transpose((1,0))
print('c0:',c0)

(2, 3) (2, 3)
a: [[1 2 3]
 [4 5 6]]
b: [[3 2 1]
 [6 5 4]]
c0: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(2, 2)


In [45]:
a = np.array([[1,2,3],[4,5,6]])
a1 = np.fliplr(a)
print(a.shape,a1.shape)
b = np.dstack((a,a1))
print('b.shape:',b.shape)
print('b:',b)
c = b.transpose((2,0,1))
print('c:',c)

d = c[:, np.newaxis, :, :]
print(c.shape,d.shape)
print('\nd:', d)

e=np.array([[1,2,3,4]])
print(e)
print(e.shape)
e=e[:,np.newaxis,:]
print(e)


(2, 3) (2, 3)
b.shape: (2, 3, 2)
b: [[[1 3]
  [2 2]
  [3 1]]

 [[4 6]
  [5 5]
  [6 4]]]
c: [[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
(2, 2, 3) (2, 1, 2, 3)

d: [[[[1 2 3]
   [4 5 6]]]


 [[[3 2 1]
   [6 5 4]]]]
[[1 2 3 4]]
(1, 4)
[[[1 2 3 4]]]


In [21]:
#4.计算
a0 = np.array([1,0,0,1,1,1])
a1 = np.array([1,0,0,0,1,0])
acc = np.mean( (a0 == a1).astype(int) )
print(acc)

# https://blog.csdn.net/u012160689/article/details/15341303
# https://zhuanlan.zhihu.com/p/33217726
c = np.dot(a0, a1) / (np.linalg.norm(a0) * np.linalg.norm(a1))  #cosin距离
print(c)
d = np.dot(a0, a1) #sum(a0i*a1i)
e = np.linalg.norm(a0) #范数？直观解释
# 默认2范数 各元素平方和的开方，计算向量长度
f = np.linalg.norm(a1)
print('d:',d)
print('e:',e)
print('f:',f)

# 1-范数，向量元素绝对值之和
# 2-范数，Euclid范数（欧几里得范数，常用计算向量长度），即向量元素绝对值的平方和再开方
# 最大值-范数，所有向量元素绝对值中的最大值

0.6666666666666666
0.7071067811865475
d: 2
e: 2.0
f: 1.4142135623730951
